### PR TITLE
I saw some iisue so fixed them

### PR DESCRIPTION
**Pull request by Trainer-AJ**
Hey @git-of-aj  pls review :)

### CODE REVIEW

**Comment by git-of-aj** [comment]
@Trainer-AJ  Pls improve readme.md 
@benmaliti -- Pls check this

**Comment by benmaliti** [comment]
@Trainer-AJ That looks great

**Comment by benmaliti** [comment]
Hi @Trainer-AJ what happened ? it just ended abruptly

**Comment by git-of-aj** [comment]
@benmaliti  -- I recieved and email saying session time exceeded, now I can't join back again ! 

You can email the workshop manager Deeksha regarding this - Deeksha.BL@knowledgehut.com

Also, you can raise complaint on prism portal..

**Comment by benmaliti** [comment]
@git-of-aj no worries, i think because of the time adjustments as clocks have moved an hour ahead now.

**Pull request closed without merging**
